### PR TITLE
arangodb-java-driver-384 "java.net.SocketException: Socket closed"

### LINKED ISSUE #384: "java.net.SocketException: Socket closed" when in a cluster mode + Docker + acquireHostList enabled
The issue was first discovered here AbsaOSS/spline#869

The error occurs in the combination of circumstances: Cluster mode + Docker + `acqureHostList=true`

My understanding of what is happening is the following.
When the VST connection is established the respective `HostHandler` asks `VstCommunication` class to refresh the host list from the server. When the new hosts are added to the set, the old ones (unless are pointing to exactly the same `ip:port`) are immediately discarded along with all associated connection pools and sockets.
The problem is that the connection instance, that has just been created and triggered the host list refreshing process in the first place, the one that is being returned from the `VstCommunication.connect()` method holds a pointer to the host that might have just been discarded (and the associated socket closed) during this host list refreshing routine. As a result in this circumstances the `VstCommunication.connect()` method returns a connection that is dead on the moment of creation, with all the consequences.

This is exactly what happens when ArangoDB runs in a virtualized environment (Docker in our case) when the networking is organized in a way that the client process addresses the server via a different IP (or a host name) that the server sees from inside its network.

The issue is reproducible by spinning up a DB cluster via `arangodb-starter` in a Docker, and run `ArangoDBTest.execute_acquireHostList_enabled()` test method against it.

### PR DESCRIPTION
**Pull request by wajda**
fixes #384 

Before returning a connection instance to the caller of the `connect()` method, check if the connection obtained from the host handler is still alive (i.e. is the associated socket is open), otherwise discard it and get a new one until a usable connection is found.

### CODE REVIEW

**Comment by wajda** [comment]
Hi Michele,
Did you have chance to take a look at the PR?
This issue holds our project release. I wonder if I should wait for the fixed upstream version, or should I proceed with a fork?

File: src/main/java/com/arangodb/internal/velocystream/VstCommunication.java [hunk 1]
```diff
@@ -92,6 +92,13 @@ protected synchronized C connect(final HostHandle hostHandle, final AccessType a
                         tryAuthenticate(connection);
                     }
                     hostHandler.confirm();
+                    if (!connection.isOpen()) {
+                        // see https://github.com/arangodb/arangodb-java-driver/issues/384
+                        connection.close();
```
Comment (rashtao) [inline src/main/java/com/arangodb/internal/velocystream/VstCommunication.java:97]:
```suggestion
```
The connection here should be already closed.

Comment (wajda) [reply src/main/java/com/arangodb/internal/velocystream/VstCommunication.java]: Thanks. Fixed!
(just being over-protective not to leave anything behind) :)
