### PR TITLE
fixed exceptions handling during shutdown

### LINKED ISSUE #399: Exception thrown from "executor.disconnect()" leads to CommunicationProtocol remaining open
```java
@Override
    public void shutdown() throws ArangoDBException {
        try {
            executor.disconnect();
            cp.close(); // <---- This is not called when the previous method throws an exception !!!
        } catch (final IOException e) {
            throw new ArangoDBException(e);
        }
    }
```

When an exception is thrown from the `executor.disconnect()` (for instance `401 - unauthorized`) the `CommunicationProtocol.close()` isn't called and thus all the associated with it resources (apparently including thread pools or such) remain unclosed. This leads to the client app being unable to exit normally.

AN easy workaround is to call `shutdown()` in a try-catch block and repeat the call on `ArangoDBException` like this:

```scala
    try {
      arango.shutdown()
    } catch {
      case _: ArangoDBException =>
        arango.shutdown()
    }
```

It would be good however, to handle exceptions internally in the driver and do a proper cleanup.

### PR DESCRIPTION
**Pull request by rashtao**
Improved exception handling during shutdown by:
- removing requests to acquire the host list before shutdown and caching the last acquire host list
- closing connections in finally block

fixes #399

### CODE REVIEW

File: src/main/java/com/arangodb/async/internal/ArangoExecutorAsync.java [hunk 1]
```diff
@@ -70,8 +71,12 @@ public ArangoExecutorAsync(final VstCommunicationAsync communication, final Aran
                 .thenApplyAsync(responseDeserializer::deserialize);
     }
 
-    public void disconnect() throws IOException {
-        communication.close();
-        outgoingExecutor.shutdown();
+    public void disconnect() {
+        try {
+            communication.close();
```
Comment (wajda) [inline src/main/java/com/arangodb/async/internal/ArangoExecutorAsync.java:76]: Shouldn't  `communication.close()` be wrapped with a separate `try-catch` as well?

Comment (rashtao) [reply src/main/java/com/arangodb/async/internal/ArangoExecutorAsync.java:76]: right, I moved the executor service shutdown inside a finally block
